Reporting/Models/Contact/ContactViewModel.cs
using InsideReporting.Controllers;

namespace InsideReporting.Models.Contact
{
    public class ContactViewModel: SiriusReportModel
    {
        public int ContactId { get; set; }
    }
}

Reporting/Controllers/SiriusController.cs
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;
using Inside.membership;
using InsideModel.Models;
using InsideModel.repositories;
using InsideReporting.Helpers;
using InsideReporting.Models.Contact;
using Microsoft.AspNet.Identity;

namespace InsideReporting.Controllers
{
    public class SiriusController : AuthenticationController
    {
        private readonly IRepository<Client> clientRepository;
        private readonly IIdentityMembershipProvider userManager;

        public SiriusController(IRepository<Client> clientRepository, IIdentityMembershipProvider userManager)
            : base(userManager)
        {
            this.clientRepository = clientRepository;
            this.userManager = userManager;
        }

        // GET: Sirius

        [Authorize(Roles = "demo,sales,consultant,client")]
        [AuthorizeClientAccess]
        public ActionResult Overview(int clientId )
        {
            var client = clientRepository.Single(c => c.Id == clientId);
            var model = new SiriusReportModel();

            model.ClientId = client.Id;
            model.ClientName = client.Name;
            model.UserId = this.User.Identity.GetUserId();
            model.HasCustomEvents = client.Labels.Any(cl => cl.Name == "Custom Event");
            model.HasAdminMenu = this.User.IsInRole("sales") || this.User.IsInRole("consultant");
            model.HasWebTab = client.Labels.Any(l => l.Name == "Webbflik");

            return View(model);
        }

        [Authorize(Roles = "demo,sales,consultant,client")]
        [AuthorizeClientAccess]
        public ActionResult ContactList(int clientId)
        {
            var model = new SiriusReportModel();
            var client = clientRepository.Single(c => c.Id == clientId);
            model.ClientId = client.Id;
            model.ClientName = client.Name;
            model.UserId = this.User.Identity.GetUserId();
            model.HasCustomEvents = client.Labels.Any(cl => cl.Name == "Custom Event");
            model.HasAdminMenu = this.User.IsInRole("sales") || this.User.IsInRole("consultant");
            model.HasWebTab = client.Labels.Any(l => l.Name == "Webbflik");
            return View(model);
        }

        [Authorize(Roles = "demo,sales,consultant,client")]
        [AuthorizeClientAccess]
        public ActionResult WebTab(int clientId)
        {
            var model = new SiriusReportModel();
            var client = clientRepository.Single(c => c.Id == clientId);
            model.ClientId = client.Id;
            model.ClientName = client.Name;
            model.UserId = this.User.Identity.GetUserId();
            model.HasAdminMenu = this.User.IsInRole("sales") || this.User.IsInRole("consultant");
            model.HasWebTab = client.Labels.Any(cl => cl.Name == "Webbflik");
            return View(model);
        }

        [Authorize(Roles = "demo,sales,consultant,client")]
        [AuthorizeClientAccess]
        public ActionResult Campaign(int clientId)
        {
            var model = new SiriusReportModel();
            var client = clientRepository.Single(c => c.Id == clientId);
            model.ClientId = client.Id;
            model.ClientName = client.Name;
            model.UserId = this.User.Identity.GetUserId();
            model.HasAdminMenu = this.User.IsInRole("sales") || this.User.IsInRole("consultant");
            model.HasWebTab = client.Labels.Any(l => l.Name == "Webbflik");
            return View(model);
        }

        [Authorize(Roles = "demo,sales,consultant,client")]
        [AuthorizeClientAccess]
        public ActionResult Contact(int clientId, int contactId)
        {
            var model = new ContactViewModel();
            var client = clientRepository.Single(c => c.Id == clientId);
            model.ClientId = client.Id;
            model.ClientName = client.Name;
            model.UserId = this.User.Identity.GetUserId();
            model.ContactId = contactId;
            model.HasAdminMenu = this.User.IsInRole("sales") || this.User.IsInRole("consultant");
            model.HasWebTab = client.Labels.Any(l => l.Name == "Webbflik");
            return View(model);
        }

        [Authorize(Roles = "demo,sales,consultant,client")]
        [AuthorizeClientAccess]
        public ActionResult MyAccount(int clientId)
        {
            var userId = User.Identity.GetUserId();
            var user = userManager.FindById(userId);
            var client = clientRepository.Single(c => c.Id == clientId);

            var model = new SiriusAccountModel();
            model.ClientId = clientId;
            model.ClientName = client.Name;
            model.UserId = this.User.Identity.GetUserId();
            model.ReceiveEmail = user.ReceiveEmail != null && (bool)user.ReceiveEmail;
            model.ReceiveSms = user.ReceiveSms != null && (bool)user.ReceiveSms;
            model.Phone = user.Phone;
            model.HasAdminMenu = this.User.IsInRole("sales") || this.User.IsInRole("consultant");
            model.HasWebTab = client.Labels.Any(l => l.Name == "Webbflik");

            return View(model);
        }

        [Authorize(Roles = "sales,consultant,client")]
        [AuthorizeClientAccess]
        [HttpPost]
        public ActionResult MyAccount(SiriusAccountModel model)
        {
            var updateMessage = new SettingUpdateMessage();
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                var user = userManager.FindById(userId);

                model.ReceiveEmail = user.ReceiveEmail != null && (bool)user.ReceiveEmail;
                model.ReceiveSms = user.ReceiveSms != null && (bool)user.ReceiveSms;
                model.Phone = user.Phone;

                var validUser = userManager.ValidateAndReturnUser(user.UserName, model.OldPassword);
                if (validUser != null)
                {
                    var succeed = userManager.UpdatePassword(validUser.Id, model.Password);
                    if (succeed)
                    {
                        updateMessage.Type = AccountMessageType.Success;
                        updateMessage.MessageText = "Uppdaterade lösenordet";
                    }
                    else
                    {
                        updateMessage.Type = AccountMessageType.Error;
                        updateMessage.MessageText = "Lösenordet uppdaterades inte";
                    }
                }
                else
                {

                    updateMessage.Type = AccountMessageType.Error;
                    updateMessage.MessageText = "Felaktigt lösenord";
                }
                model.Message = updateMessage;
                return View(model);
            }

            updateMessage.Type = AccountMessageType.Error;
            updateMessage.MessageText = "Lösenordet uppdaterades inte";
            model.Message = updateMessage;
            return View(model);
        }

        [Authorize(Roles = "sales,consultant,client")]
        [AuthorizeClientAccess]
        [HttpPost]
        public ActionResult UpdateSettings(bool receiveEmail, bool receiveSms, string phone)
        {
            var userId = User.Identity.GetUserId();
            var user = userManager.FindById(userId);

            var updateMessage = new SettingUpdateMessage();
            if (user != null)
            {
                user.ReceiveEmail = receiveEmail;
                user.ReceiveSms = receiveSms;
                user.Phone = phone;
                userManager.Update(user);
                updateMessage.Type = "Success";
                updateMessage.MessageText = "Uppdaterade inställningar";
                return Json(updateMessage, JsonRequestBehavior.AllowGet);
            }

            updateMessage.Type = "Error";
            updateMessage.MessageText = "Oväntat fel";
            return Json(updateMessage, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "demo,sales,consultant")]
        [AuthorizeClientAccess]
        public ActionResult Demo()
        {
            return RedirectToAction("ContactList", new { clientId = 1 });
        }
    }

    public class SiriusReportModel
    {
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public string UserId { get; set; }
        public bool HasCustomEvents { get; set; }
        public bool HasAdminMenu { get; set; }
        public bool HasWebTab { get; set; }
    }

    public class SiriusAccountModel : SiriusReportModel
    {
        public SettingUpdateMessage Message { get; set; }

        [Display(Name = "Telefonnumber")]
        public string Phone { get; set; }

        [Display(Name = "Jag vill ha e-post")]
        public bool ReceiveEmail { get; set; }

        [Display(Name = "Jag vill ha SMS")]
        public bool ReceiveSms { get; set; }

        [Required(ErrorMessage = "Du måste ange ditt gamla lösenord")]
        [DataType(DataType.Password)]
        [Display(Name = "Gammalt lösenord")]
        public string OldPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Nytt lösenord")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Bekräfta ditt lösenord")]
        [System.Web.Mvc.Compare("Password", ErrorMessage = "Lösenorden stämmer inte överens.")]
        public string ConfirmPassword { get; set; }
    }

    public class SettingUpdateMessage 
    {
        public string Type { get; set; }
        public string MessageText { get; set; }
    }

    public static class AccountMessageType
    {
        public static string Success = "Success";
        public static string Error = "Error";
    }

}

Reporting/Views/Sirius/Campaign.cshtml
@model InsideReporting.Controllers.SiriusReportModel
@{
    ViewBag.Title = "Kampanjer";
    Layout = "/Views/Layout/_Sirius.cshtml";
}

<header class="header-container header-container-active" id="header-filter-container">
    <div class="left-menu">
        <button class="toggle-sidebar btn-icon-only btn-empty"><i class="fa fa-bars" style=""></i></button>
    </div>
    <div class="middle-menu active-item menu-item" style="right: 110px; overflow-x: hidden !important;">
        <a href="#" class="active-item menu-item right-menu-item dropdown-toggle" id="dropdownMenu2">
            <span class="dropdown-title">Kampanjer</span>
        </a>
        
    </div>
    <div class="dropdown" >
        <ul class="dropdown-menu dropdown-menu-large" role="menu" id="dropdownMenuList" style="min-height: 50px; left: 25px;">
            <li class="current campaign-report" role="presentation"><a role="menuitem" tabindex="-1" >Kampanjer</a></li>
            <li class="divider" role="presentation"></li>
            <li class="keyword-report" role="presentation"><a role="menuitem" tabindex="-1">Sökord</a></li>
        </ul>
    </div>
    <div class="right-menu" style="width: 110px;">

    </div>
    
</header>



<section class="main-content" id="main-content">
    <div class="row" style="max-width:1300px;min-height:50%;">
        <article class="col-xs-12" style="min-height:50%">
            
            <header class="display-when-header">
                <h2>
                    <span id="header-description"></span>
                    <span class="month-name"></span>
                </h2>

            </header>

            <header class="hidden-when-header">
                <h2>
                    <span class="header-title ">Kampanjer</span> <div class="month-name" style="display: inline-block;"></div>
                    <div class="btn-group pull-right" id="date-picker"></div>
                    <div class="btn-group pull-right" style="padding-right: 15px">
                        <label class="btn btn-default active campaign-report">
                            <span>Kampanjer</span>
                        </label>
                        <label class="btn btn-default keyword-report">
                            <span>Sökord</span>
                        </label>
                    </div>
                </h2>

            </header>
            <section class="widget" id="campaign-table"></section>
            <section class="widget" id="keyword-table"></section>

            <section class="widget" id="campaign-list"></section>
            <section class="widget" id="keywords-list"></section>
        </article>
    </div>
</section>


<script type="text/javascript">
    $(function () {
        
        $('body').reportselector({
            clientId: '@Model.ClientId'
        });
        $('body').screenresize();

        $('.month-name').ReportName('MMMM');
      
        $(document).bind("campaignReport", function() {
            $('span.header-title').html('Kampanjer');
            $('#header-description').html('');
            $('span.dropdown-title').html('Kampanjer');

            $('ul#dropdownMenuList li').removeClass('current');
            $('ul#dropdownMenuList li.campaign-report').addClass('current');

            $('header .btn.keyword-report').removeClass('active');
            $('header .btn.campaign-report').addClass('active');
        });

        $(document).bind("keywordReport", function () {
            $('span.header-title').html('Topp Sökord');

            $('#header-description').html('Topp ');
            $('span.dropdown-title').html('Sökord');

            $('ul#dropdownMenuList li').removeClass('current');
            $('ul#dropdownMenuList li.keyword-report').addClass('current');
            
            $('header .btn.campaign-report').removeClass('active');
            $('header .btn.keyword-report').addClass('active');

        });

        $('body').click(function() {
            $('ul#dropdownMenuList').hide();
        });

        $('#dropdownMenu2').click(function (event) {
            event.stopImmediatePropagation();
            $('ul#dropdownMenuList').toggle();
        });

        $('.keyword-report').click(function () {
            $('ul#dropdownMenuList').hide();
            $(document).trigger("keywordReport");
        });

        $('.campaign-report').click(function () {
            $('ul#dropdownMenuList').hide();
            $(document).trigger("campaignReport");
        });

        $('#date-picker').ReportDatePicker();
        $('.right-menu').ReportDatePicker("mini");

        $('#campaign-link').addClass('active');
        $('#campaign-table').campaigntable();
        $('#keyword-table').keywordtable();
        $('#campaign-list').campaignlist();
        $('#keywords-list').keywordslist();

    });
</script>

Reporting/Views/Sirius/Contact.cshtml
@model InsideReporting.Models.Contact.ContactViewModel
@{
    ViewBag.Title = "Resultat";
    Layout = "/Views/Layout/_Sirius.cshtml";
}

@Html.Partial("/Views/Layout/_SiriusTitlebar.cshtml", "Kontakt")

<section class="main-content" id="main-content">
    <div class="row" style="max-width:1300px;min-height:100%;">
        <article id="contact-widget" class="col-xs-12  col-lg-8 "></article>
        <article class="col-xs-12  col-lg-8 ">
            <header >
                <div class="btn btn-default">
                    <i class="fa fa-chevron-left"></i>
                    <a href="/report/@Model.ClientId/contact" style="color: white; text-decoration: none">Alla kontakter</a>
                </div>
            </header>
        </article>
    </div>
</section>


@section scripts{
    <script type="text/javascript">
        $(function() {
            $('body').screenresize();

            $('body').reportselector({
                clientId: '@Model.ClientId'
            });
            $('body').contactdata();
            $('#contact-widget').contact({contactId:@Model.ContactId});
        });
    </script>
}

Reporting/Views/Sirius/ContactList.cshtml
@model InsideReporting.Controllers.SiriusReportModel

@{
    ViewBag.Title = "Resultat";
    Layout = "/Views/Layout/_Sirius.cshtml";
}

<header class="header-container header-container-active" id="header-filter-container">
    <div class="left-menu">
        <button class="toggle-sidebar btn-icon-only btn-empty"><i class="fa fa-bars" style=""></i></button>
    </div>

    <div class="dropdown middle-menu" style="display:inline-block;">
        <a href="#" class="active-item menu-item dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown">
            <span class="menu-header-text">Alla Kontakter </span>
            <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-menu-large" role="menu" aria-labelledby="dropdownMenu1" style="max-height: 400px; min-width: 160px;">
            <li class="current" role="presentation"><a class="dropdown-menu-item"  role="menuitem" tabindex="-1" href="/report/@Model.ClientId/contact" data-text="Alla Kontakter">Alla Kontakter</a></li>
            <li class="divider" role="presentation"></li>
            <li role="presentation"><a class="dropdown-menu-item"  role="menuitem" tabindex="-1" href="/report/@Model.ClientId/contact?status=new" data-text="Nya Kontakter">Nya Kontakter</a></li>
            <li class="divider" role="presentation"></li>
            <li role="presentation"><a class="dropdown-menu-item" role="menuitem" tabindex="-1" href="/report/@Model.ClientId/contact?type=Phone" data-text="Telefon">Telefon</a></li>
            <li role="presentation"><a class="dropdown-menu-item" role="menuitem" tabindex="-1" href="/report/@Model.ClientId/contact?type=Chat" data-text="Chat">Chat</a></li>
            <li role="presentation"><a class="dropdown-menu-item" role="menuitem" tabindex="-1" href="/report/@Model.ClientId/contact?type=Email" data-text="E-post">E-post</a></li>
            @if (Model.HasCustomEvents)
            {
                <li role="presentation"><a class="dropdown-menu-item" role="menuitem" tabindex="-1" href="/report/@Model.ClientId/contact?type=Event" data-text="Event">Event</a></li>
            }
            <li class="divider" role="presentation"></li>
            <li role="presentation"><span class="dropdown-menu-item" role="menuitem" tabindex="-1" href="#" id="show-contact-labels">Etiketter <i class="fa fa-caret-right"></i></span></li>
            <li class="divider" role="presentation"></li>
            <li class="labels" role="presentation"><a class="dropdown-menu-item" role="menuitem" tabindex="-1" href="/report/@Model.ClientId/contact?product=Search" data-text="Search">Search</a></li>
            <li class="labels" role="presentation"><a class ="dropdown-menu-item" role="menuitem" tabindex="-1" href="/report/@Model.ClientId/contact?product=Display" data-text="Display">Display</a></li>
            <li class="labels" role="presentation"><a class="dropdown-menu-item" role="menuitem" tabindex="-1" href="/report/@Model.ClientId/contact?product=Retargeting" data-text="Retargeting">Retargeting</a></li>
            <li class="labels" role="presentation"><a class="dropdown-menu-item" role="menuitem" tabindex="-1" href="/report/@Model.ClientId/contact?product=Organic" data-text="Organic">Organic</a></li>
        </ul>
    </div>
</header>

<header class="header-container header-container-select" id="header-select-container" style="display: none;">
   
</header>

<section class="main-content" id="main-content">
    <div class="row" style="max-width:1300px;min-height:100%;">
        <div class="col-xs-12" style="min-height:100%">
            <header class="hidden-when-header">
                <h2 >
                    <span id="text">Mina kontakter</span>
                    <div id="filter-groups" class="labels-container">
                    </div>
                    <button id="export-all-contacts" type="button" class="btn btn-default pull-right">Exportera <i class="fa fa-cloud-download"></i></button>
                    <div class="dropdown dropdown-lg" id="tag-menu">
                        <a type="button" class="btn btn-default dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown">Etiketter <i class="fa fa-tag"></i></a>
                    </div>
                </h2>
            </header>
            <section class="widget">
                <div class="container-fluid" id="contact-table">
                </div>
                
                <div id="contact-list">
                </div>
            </section>
        </div>
    </div>
</section>


@section scripts{

    <script type="text/javascript">
        $(function () {
            $('body').screenresize();

            $('body').reportselector({
                clientId: '@Model.ClientId'
            });

            $('body').contactdata();
            $('body').selecteddata();
            $('#header-select-container').selectHeader();
            $('#contact-table').contacttable();
            $('#contact-list').contactlist();
            $('#tag-menu').selectMenu();
            $('#contact-link').addClass('active');

            $('#export-all-contacts').click(function() {
                $(document).trigger('showExportModal');
            });

            $('.dropdown-menu-large .labels').hide();
            $('#show-contact-labels').on("click", function (event) {
                event.preventDefault();
                event.stopPropagation();
                $('.dropdown-menu-large .labels').toggle();
                if ($('#show-contact-labels i').hasClass('fa-caret-right')) {
                    $('#show-contact-labels i').removeClass('fa-caret-right').addClass('fa-caret-down');
                } else {
                    $('#show-contact-labels i').removeClass('fa-caret-down').addClass('fa-caret-right');
                }
            });

            $('.dropdown').ReportFilter(function (headerText) {
                if (headerText.toLowerCase() != "alla kontakter") {
                    $('header span#text').html("Mina Kotakter:");
                    $('#filter-groups').append(' <a href="/report/' + '@Model.ClientId' + '/contact" class="btn btn-default"><i class="fa fa-times" style="padding-right: 4px;"></i>' + headerText + '</a>');
                }
            });


            $(document).bind("selectedItemsChanged", function (event, items) {
                if (items.selected.length > 0) {
                    $('#header-filter-container').hide();
                } else {
                    $('#header-filter-container').show();
                }
            });
    });
    </script>
}

Reporting/Views/Sirius/MyAccount.cshtml
@using System.Web.Optimization
@using InsideReporting.Controllers
@model InsideReporting.Controllers.SiriusAccountModel
@{
    ViewBag.Title = "Mitt konto";
    Layout = "/Views/Layout/_Sirius.cshtml";
}

@Html.Partial("/Views/Layout/_SiriusTitlebar.cshtml", "Mitt konto")

<section class="main-content" id="main-content">
    <div class="row" style="max-width:1300px;min-height:100%;">
        <div class="col-xs-12 col-lg-8" style="min-height:50%">
            <article id="settings"></article>
            <article id="password">
                <header >
                    <h2>Lösenord</h2>
                </header>
                
                <section class="widget" id="my-account">
                    @using (Html.BeginForm("MyAccount", "Sirius", new { role = "form" }, FormMethod.Post, new { @class = "left-form" }))
                    {
                        if (Model.Message != null && Model.Message.Type == "Error")
                        {

                            @Html.ValidationSummary(@Model.Message.MessageText, new { @class = "text-danger" })
                        }
                        @Html.HiddenFor(model => model.ClientId)
                        @Html.HiddenFor(model => model.ReceiveEmail)
                        @Html.HiddenFor(model => model.ReceiveSms)
                        @Html.HiddenFor(model => model.Phone)
                        <div class="form-group">
                            @Html.LabelFor(m => m.OldPassword)
                            <div>
                                @Html.PasswordFor(m => m.OldPassword, new { @class = "form-control ", @placeholder = "Gammalt lösenord" })
                                @Html.ValidationMessageFor(model => model.OldPassword, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.Password)
                            <div>
                                @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Nytt lösenord" })
                                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.ConfirmPassword)
                            <div>
                                @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control ", @placeholder = "Bekräfta ditt lösenord" })
                                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group" style="text-align: right;">
                            <input type="submit" class="btn btn-success" value="Spara" />
                        </div>
                    }
                </section>
            </article>
            
        </div>
    </div>
</section>

@section scripts{
    <script type="text/javascript">
        $(function () {
            $('body').screenresize();

            $('body').reportselector({
                clientId: '@Model.ClientId'
            });

            $('#my-account-link').addClass('active');
            $('#settings').account({
                receiveEmail: '@Model.ReceiveEmail',
                receiveSms: '@Model.ReceiveSms',
                phoneNumber: '@Model.Phone',
            });
        });

    </script>
}

<script type="text/javascript">
    $(function () {
        @if (Model.Message != null && Model.Message.Type=="Success")
        {
            <text>
                var alertBox = $('<div class="alert alert-success alert-dismissible" id="success-alert" role="alert">' +
                  '<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>' +
                  '<p>@Model.Message.MessageText</p>' +
                  '</div>');
                    alertBox.appendTo($('#password header'));
                    alertBox.alert();
                setTimeout(function () {
                    alertBox.alert('close');
                }, 2000);
        
            </text>
        }

    });
</script>

Reporting/Views/Sirius/Overview.cshtml
@model InsideReporting.Controllers.SiriusReportModel
@{
    ViewBag.Title = "Resultat";
    Layout = "/Views/Layout/_Sirius.cshtml";
}

@Html.Partial("/Views/Layout/_SiriusTitlebar.cshtml", "Resultat")

<section class="main-content" id="main-content">
    <div class="row" style="max-width:1300px;min-height:100%;">
        <article id="flow-widget" class="col-xs-12  col-lg-7 "></article>
        <article id="chart-widget" class="col-xs-12 col-lg-5 "></article>

    </div>
</section>

@section scripts{
    <script type="text/javascript">
        $(function () {
            $('body').screenresize();

            $('body').reportselector({
                clientId: '@Model.ClientId'
            });

            $('#overview-link').addClass('active');
            $('#flow-widget').flowSummary({ showCustomContacts: '@Model.HasCustomEvents' });
            $('#chart-widget').overviewChart({ showCustomContacts: '@Model.HasCustomEvents' });
        });
    </script>
}